name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build Jekyll site
        run: bundle exec jekyll build --future
        env:
          JEKYLL_ENV: production
